name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}  # キャッシュヒット情報を次のジョブに渡す

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    # キャッシュの設定
    - id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'  # キャッシュがヒットしなかった場合のみnpm installを実行
      run: npm install

  test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restore node_modules from cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Run Jest
      run: npm test --watchAll=false --coverage

  lint:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restore node_modules from cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Run ESLint
      run: npm run lint:eslint
