name: Jest

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  Test:
    name: Run test codes
    if: |
      github.event.pull_request.draft == false
      && !startsWith(github.head_ref, 'release')
      && !startsWith(github.head_ref, 'doc')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - uses: actions/setup-node@v3
      - name: Install packages
        run: npm install
      - name: Run test and show coverage
        run: npm test --watchAll=false --coverage
